### ISSUE TITLE
Incorrect package json exports in @equinor/fusion-framework-module-app

### ISSUE THREAD

**Issue by espenhm** [equinor/fusion-framework#1968]
**Describe the bug**
When adding eslint to our migration to Vite we were faced with this issue error message.
![image](https://github.com/equinor/fusion-framework/assets/31277486/52d6a1ef-943d-4791-8fdd-cdbd1b1e8a0c)
Tried to remove our eslint commit and it works like expected then. This issue seems similar to: https://github.com/equinor/fusion-framework/issues/1954

**Environment**

- OS (windows, mac, linux)
mac and windows

- Node Version
v16.14.1

**To Reproduce**
Steps to reproduce the behavior
Adding these imports and versions to our new Vite project. 
![image](https://github.com/equinor/fusion-framework/assets/31277486/61947e49-2016-4039-a02c-ed211f4eb179)

**Stacktrace**
```
[vite] Internal server error: Package subpath './dist/types/types' is not defined by "exports" in /Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/@equinor/fusion-framework-module-app/package.json
Occurred while linting /Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/src/index.ts:1
Rule: "import/namespace"
  Plugin: vite-plugin-eslint
  File: /Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/src/index.ts
      at formatError (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50647:46)
      at TransformContext.error (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50641:19)
      at TransformContext.transform (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite-plugin-eslint/dist/index.mjs:1:1989)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.transform (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:50956:30)
      at async loadAndTransform (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:53746:29)
      at async viteTransformMiddleware (file:///Users/espen.meland/Documents/Projects/Equinor/plant-query/src/frontend2/node_modules/vite/dist/node/chunks/dep-jvB8WLp9.js:63522:32)
```

**Additional context**
We are facing the issue both locally and in PR env

**Comment by espenhm** [comment]
Any updates?

**Comment by eikeland** [comment]
Hei, the latest release has correct package exports now, try updating to latest.

You could also update your `@equinor/eslint-config-fusion` or change to `@equinor/eslint-config-fusion-react`. eslint config-fusion-react should install all needed eslint modules, except for eslint and prettier and any custom rules you need.

Your eslintrc file should look something like this:

```json
{
  "extends": "@equinor/eslint-config-fusion-react",
  "plugins": [],
  "rules": {}
}
```

And also change to node 18-20, 16 is deprecated now.

**Comment by espenhm** [comment]
Issue has been resolved!
